FROM ubuntu

# 환경 변수 
ENV SERVICE_ROOT /home
ENV SERVICE_VENV venv
ENV SERVICE_DIR web

# 환경 변수를 조합해서 WORKDIR 지정
# 해당 디렉토리가 없다면 만들어서 현재 디렉토리로 이동
# mkdir, cd 를 포함한 명령
WORKDIR $SERVICE_ROOT/$SERVICE_VENV/$SERVICE_DIR

# 실행
RUN ["pwd"]

